# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: my-ingress
#   namespace: default
# spec:
#   rules:
#   - host: a807189a264f740daba16df3875f3851-1512545859.ap-northeast-2.elb.amazonaws.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: crider-service
#             port:
#               number: 8000

# ---

apiVersion: v1
kind: Service
metadata:
  name: crider-service
  namespace: default
spec:
  selector:
    app: crider-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crider-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crider-backend
  template:
    metadata:
      labels:
        app: crider-backend
    spec:
      containers:
      - name: crider-backend
        image: 381492185710.dkr.ecr.ap-northeast-2.amazonaws.com/aws-ecr-development-crider-service:latest
        ports:
        - containerPort: 8000