apiVersion: apps/v1
kind: Deployment
metadata:
  name: crider-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crider-backend
  template:
    metadata:
      labels:
        app: crider-backend
    spec:
      containers:
      - name: crider-backend
        image: 381492185710.dkr.ecr.ap-northeast-2.amazonaws.com/crider-backend:latest
        ports:
        - containerPort: 80