apiVersion: v1
kind: Service
metadata:
  name: crider-backend
  namespace: default
spec:
  selector:
    app: crider-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP