apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crider-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    # - host: nlb-test-b20cc363ee6a1c89.elb.ap-northeast-2.amazonaws.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: crider-service
              port:
                number: 80
