apiVersion: v1
kind: Service
metadata:
  name: crider-service
  namespace: default
spec:
  selector:
    app: crider-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
