apiVersion: apps/v1
kind: Deployment
metadata:
  name: crider-deployment
  labels:
    app: crider
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crider
  template:
    metadata:
      labels:
        app: crider
    spec:
      containers:
        - name: crider-backend
          image: 381492185710.dkr.ecr.ap-northeast-2.amazonaws.com/crider-backend:latest
          ports:
            - containerPort: 80
